# Generated by Django 5.2.5 on 2025-08-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('soil_moisture', models.IntegerField()),
                ('temprature', models.FloatField()),
                ('rain', models.FloatField()),
                ('irrigation_needed', models.BooleanField(default=False)),
                ('humidity', models.FloatField()),
            ],
        ),
    ]
